### ISSUE TITLE
Call to member function

### ISSUE THREAD

**Issue by kezern** [Sopamo/laravel-filepond#17]
I have just started a new laravel project andI'm trying to use filepond for file uploading. I have installed this library following composer instrucctions and it seems fine, but when I try to upload an image I get a 500 error in my frontend and looking in laravel logs I get this message.

> local.ERROR: Call to a member function extension() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function extension() on null at C:\\laragon\\www\\filepond\\vendor\\sopamo\\laravel-filepond\\src\\Http\\Controllers\\FilepondController.php:37)
[stacktrace]
#0 [internal function]: Sopamo\\LaravelFilepond\\Http\\Controllers\\FilepondController->upload(Object(Illuminate\\Http\\Request))
#1 C:\\laragon\\www\\filepond\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#2 C:\\laragon\\www\\filepond\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('upload', Array)

Here is my html code
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">

    

    
    <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
    <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">

    <style>
        /* FilePond will automatically fill up all available horizontal space, it's best to limit it in some way */
        form {
            max-width:24em;
        }
    </style>
</head>
<body>
    
    <form action="api/submit.php" method="post" enctype="multipart/form-data">

        <input type="file" name="filepond[]" multiple>

        <button type="submit">Submit</button>
    
    </form>

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>

    
    <script src="https://unpkg.com/filepond-polyfill/dist/filepond-polyfill.js"></script>
  
   
    
    <script src="https://unpkg.com/filepond/dist/filepond.js"></script>
    <script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-resize/dist/filepond-plugin-image-resize.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-crop/dist/filepond-plugin-image-crop.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.js"></script>
    
    
    <script>

    // Register plugins
    FilePond.registerPlugin(
        FilePondPluginFileValidateSize,
        FilePondPluginImageExifOrientation,
        FilePondPluginImageCrop,
        FilePondPluginImageResize,
        FilePondPluginImagePreview,
        FilePondPluginImageTransform
    );
    
    // Set default FilePond options
    FilePond.setOptions({

        // maximum allowed file size
        maxFileSize: '3MB',

        // crop the image to a 1:1 ratio
        //imageCropAspectRatio: '1:1',

        // resize the image
        //imageResizeTargetWidth: 200,

        // upload to this server end point
        //server: 'api/'
        server: {
            url: '/filepond/api',
            process: '/process',
            headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
            }
        }
    });

    // Turn a file input into a file pond
    var pond = FilePond.create(document.querySelector('input[type="file"]'));

    </script>

</body>
</html>`

**Comment by AhmedFawzy** [comment]
Seems that the input name is hardcodes to file
Just change the input file to file for now
<input type="file" name="file[]" multiple>
