### ISSUE TITLE
Publish the configuration file to edit it

### ISSUE THREAD

**Issue by st-kovalenko** [Sopamo/laravel-filepond#23]
I use this command to publish the configuration file
`php artisan vendor:publish --provider="Sopamo\LaravelFilepond\LaravelFilepondServiceProvider"`
and I get "Unable to locate publishable resources." back.

When I execute the following command `php artisan vendor:publish` then I don't get an entry with "Sopamo\LaravelFilepond\LaravelFilepondServiceProvider".

Laravel Framework 6.15.1
PHP 7.2.1

I'm doing something wrong?

**Comment by Sopamo** [comment]
Are you sure that the package is installed correctly via composer? Does the file exist in your vendor folder?

**Comment by st-kovalenko** [comment]
The package was installed successfully without error output. The files exist in the vendor folder.
Tried in two separate Laravel installations.

**Comment by gautamsolankidev** [comment]
Having Same Issue.

**Comment by Sopamo** [comment]
For now you can manually copy the configuration file. I'll look into it when I have some spare time.

**Comment by leandrochl** [comment]
Any updates about this issue?

**Comment by st-kovalenko** [comment]
Unfortunately I have no further information...

> 
> 
> Any updates about this issue?

**Comment by leandrochl** [comment]
#19 solved this issue. It would be nice to merge.

**Comment by Sopamo** [comment]
This has been fixed in v0.4.
