### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by neodisco** [Sopamo/laravel-filepond#33]
Hi Paul! Thank you for your great contribution!

Can I ask how you intend for this library to be used?

In the readme you say "_to be used in your own controller to move the file from temporary storage to somewhere permanent using the `getPathFromServerId` function_”. 

However if I extend your controller, I can't access your `private $filepond` variable to run the  `getPathFromServerId` method. 

I'm also of the understanding a controller should never call another controller either. Let me know!

**Comment by keatliang2005** [comment]
hi,

actually you don't need to extend the controller, the controller already have route loaded on service provider

https://github.com/Sopamo/laravel-filepond/blob/master/routes/web.php

all you need to is upload the file to the endpoint, then in the controller use the Filepond instance to retrieve the file path. 
as stated in the readme on the php code snippes
https://github.com/Sopamo/laravel-filepond/blob/master/README.md

hope this helps :)

**Comment by neodisco** [comment]
Don't worry I have read the readme a dozen times. I still don't get it :) 

> all you need to is upload the file to the endpoint

Do you mean, have your Filepond Javascript instance send the data to /process? Ok, got that, and it returns getServerIdFromPath() to the Javascript instance.

> then in the controller 

In which controller? My own? How would my controller know when the files have been uploaded? Maybe my mind hasn't wrapped around this because my use case doesn't involve a separate form submission that would hit "my own" controller (I'm uploading files immediately).

**Comment by keatliang2005** [comment]
> Do you mean, have your Filepond Javascript instance send the data to /process? Ok, got that, and it returns getServerIdFromPath() to the Javascript instance.

yes, once POST to process, upon success, you get HTTP 200 with plan text respond with a encrypted string, that string is the ID.


> In which controller? My own? How would my controller know when the files have been uploaded? How would it know what files have been uploaded? Maybe my mind hasn't wrapped around this because my use case doesn't involve a separate form submission that would hit "my own" controller (I'm uploading files immediately).

once after POST to /process, you got the serverID (long encrypted string), then post again in the endpoint of your choice, usually your endpoint with the controller, use that to get the file path

example: 
step 1, upload to /process, and get {serverID}
step 2, submit data to designated endpoint with the serverID

Frontend
```
POST /create (map to your controller of choice)
{
 "name": "John Doe",
"picture":"{serverID}"
}
```

backend
```php
$picture = $request->input('picture');
$filepond = app(Sopamo\LaravelFilepond\Filepond::class); //make Filepond instance
$path = $filepond->getPathFromServerId($picture );

// Move the file from the temporary path to the final location
$finalLocation = public_path('output.jpg');
\File::move($path, $finalLocation);
```

**Comment by neodisco** [comment]
Thanks! Perfect. This is a very different way of performing the request than I had imagined, and makes complete and logical sense now that you explain it. My mind was in having the back-end process and store each upload instantly as it came in, rather than having the front end keep track of all the uploads and submit a later request.

**Comment by Sopamo** [comment]
@neodisco I'm not quite sure if you understood the workflow correctly. Filepond is actually uploading the image as soon as the user selects it.
When you are ready to submit your form (where the user might be able to enter more data) you can get the server ids from filepond with your custom js and submit those to your controller where you use them like @keatliang2005 described in the "backend" section.
You can find more information on how to interact with filepond on the clientside in the [official filepond repo](https://github.com/pqina/filepond)

**Comment by neodisco** [comment]
Correct, this was the issue - I'm not wanting to use a upload->submit workflow, just instant upload.

**Comment by Sopamo** [comment]
This would be possible as well, as you could listen for the event when the upload is finished and then immediately submit the server id to your controller. However, that has nothing to do with `laravel-filepond` but happens only on the side of filepond itself.

**Comment by interludic** [comment]
What about abandoned files left behind and clean up?
