### ISSUE TITLE
Laravel 8.0 support

### ISSUE THREAD

**Issue by chrismackie28** [Sopamo/laravel-filepond#37]
Hi, do you have plans to update this to support the latest version of Laravel?

**Comment by Sopamo** [comment]
Yes, it will take me a few days, if someone can test it in a L8 project (should work fine as is) and create a PR it might be faster.

**Comment by Sopamo** [comment]
Found some time to do this [right away](https://github.com/Sopamo/laravel-filepond/releases/tag/v0.5.0)
