### ISSUE TITLE
Restore example?

### ISSUE THREAD

**Issue by AndreasElia** [Sopamo/laravel-filepond#51]
Hey, awesome package and very useful.

I'm working on adding "restore" functionality, but ran into an issue where filepond always displays "upload complete" for chunked files.

As you can see from the below code, I return the file and header as expected via the filepond documentation.

```php
public function restore(Request $request, string $id)
{
    $disk = config('filepond.temporary_files_disk', 'local');
    $path = config('filepond.temporary_files_path', 'filepond').DIRECTORY_SEPARATOR.$id;

    $mime = Storage::disk($disk)->mimeType($path);
    $file = Storage::disk($disk)->get($path);

    return Response::make($file, 200, [
        'Content-Type' => $mime,
        'Content-Disposition' => 'inline; filename="'.$id.'"',
    ]);
}
```

Routes (overwritten):

```php
// Filepond
Route::prefix('filepond')->group(function () {
    Route::patch('/', [FilepondController::class, 'chunk'])->name('filepond.chunk');
    Route::post('/process/{video}', [FilepondController::class, 'upload'])->name('filepond.upload');
    Route::delete('/process/{video}', [FilepondController::class, 'delete'])->name('filepond.delete');
    Route::get('/restore/{id}', [FilepondController::class, 'restore'])->name('filepond.restore');
});
```

Frontend JS:

```js
FilePond.setOptions({
    chunkUploads: true,
    server: {
        url: '/filepond',
        process: '/process/{{ $video->id }}',
        revert: '/process/{{ $video->id }}',
        restore: '/restore/',
        headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}',
        }
    },
});

const inputElement = document.querySelector('.filepond');
const pond = FilePond.create(inputElement, {
    files: [
        {
            source: '9K3Z9t0DSEU4tfFI', // example chunk id
            options: {
                type: 'limbo',
            },
        },
    ],
});
```

Visiting the page with filepond integrated then displays:

![image](https://user-images.githubusercontent.com/5033092/121609463-d2a02280-ca4b-11eb-991e-316a04321d4b.png)

But I'd expect it to continue the upload which was interrupted.

Any suggestions would be greatly appreciated.

**Comment by iamB0rgy** [comment]
@andreaselia You closed it without fixing it coz you are fed up or you closed it because you fixed the issue and didn't want to share how you fixed it?

**Comment by andreaselia** [comment]
@iamB0rgy I don't fully remember, but if I am remembering correctly, it wasn't actually possible to do what I wanted to achieve here.

My apologies for not updating the issue when I closed it.

**Comment by iamB0rgy** [comment]
> @iamB0rgy I don't fully remember, but if I am remembering correctly, it wasn't actually possible to do what I wanted to achieve here.
> 
> My apologies for not updating the issue when I closed it.

What did you use then? Please give me an idea. I'm stuck in here. Thanks

**Comment by andreaselia** [comment]
> > @iamB0rgy I don't fully remember, but if I am remembering correctly, it wasn't actually possible to do what I wanted to achieve here.
> > My apologies for not updating the issue when I closed it.
> 
> What did you use then? Please give me an idea. I'm stuck in here. Thanks

I genuinely don't remember. I *think* we may have skipped the idea of "restoring" and instead allowed users to upload a file in its whole (and restart if it failed), and then ran a job to do what we needed to with the file afterwards, but again, I don't recall unfortunately and no longer work at the company where I was working with filepond on a project. Sorry about that.

**Comment by iamB0rgy** [comment]
No worries. I'm pretty sure the author will answer after a decade. 😁
