### ISSUE TITLE
Chunked Uploads?

### ISSUE THREAD

**Issue by xaddict** [Sopamo/laravel-filepond#52]
I can see there is a pre-release for Chunked Uploads and was wondering how this is coming along and when it will be released. I know an issue is not the best place but I couldn't find any other place to ask for progress :)

My apologies if this is considered spam.

**Comment by Sopamo** [comment]
Not considered spam :) we're already using the pre release in production ourselves, but depending on your concrete use case it might not be as fast as you'd like. There are some things which can be improved regarding performance, but only by replacing certain laravel native features with our own implementation. But especially if you are only using one server which persists files locally it should work perfectly fine. 
Please do give feedback about the feature after trying it out!

**Comment by theJsTsGuy** [comment]
@Sopamo Can you guide how can I implement chunked uploads with FilePond JS and FilePond-Laravel using the beta package? What would be configured to make it work? The readme of the beta package is the same as the stable one.
Thanks.

**Comment by Sopamo** [comment]
@theJsTsGuy it should just work if you enable chunking in filepond js.

**Comment by theJsTsGuy** [comment]
@Sopamo please also let me know how can we limit the size of file uploads, so users can't upload more than a specific size.

**Comment by Sopamo** [comment]
@theJsTsGuy regarding the endpoint, please see the documentation in the readme (the js part at the bottom). The server stores the uploaded files temporarily (see the config file on how to configure that). In your controller method you can then store the files wherever you like.
Limiting the file upload size is only possible via the JS part of filepond right now.

**Comment by Sopamo** [comment]
V1 brings support for chunked uploads
