### ISSUE TITLE
How to load already saved image?

### ISSUE THREAD

**Issue by vgavrilovikj** [Sopamo/laravel-filepond#54]
I am building a simple CRUD application where people can create new items and for each item, they should upload an image, I am using filepond and your package for uploading the image.

However, what I need help with is when I click to edit an already existing item I want to load the image that has been previously uploaded (storing the image name in the DB and on S3), how can I achieve this? @Sopamo

**Comment by Sopamo** [comment]
Sorry, this is currently not natively supported by laravel-filepond. As there are currently no plans to extend the functionality of laravel-filepond in this direction, I'm going to close this issue.
I think you might be able to implement this functionality yourself, but I think those kind of questions are better fitted for sites like stackoverflow.
If you feel like there are specific features that this library could implement to make this easier, feel free to open a PR.
