### ISSUE TITLE
Support for Laravel 9.x

### ISSUE THREAD

**Issue by Kibadda** [Sopamo/laravel-filepond#59]
Are there any planned updates to support Laravel 9.x?

**Comment by sammyaxe** [comment]
I have forked the repo and simply added the version to allow 9.x, and everything seems to work just fine.
I'm not going to do pull request as I have not tested everything and I'm not too familiar expectations.

@Kibadda if you need short term solution:

add this to your composer.json

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/sammyaxe/laravel-filepond"
        }
    ],
```

and the in require:

```
"sopamo/laravel-filepond": "dev-master"
```

that will make it install from my fork, report if you find any issues, I might be able to help fix them, and then we can make pull request.

```composer update``` after composer.json changes are done, of course.

**Comment by Sopamo** [comment]
Has been added with https://github.com/Sopamo/laravel-filepond/releases/tag/v1.1.0
