### ISSUE TITLE
the uploaded file cannot be accessed several hours later

### ISSUE THREAD

**Issue by 0length** [Sopamo/laravel-filepond#9]
i did deploy my laravel app at heroku.I use this uploader to upload jpg files. Initially all files that have been uploaded using this uploader can be used, but the uploaded file cannot be accessed several hours later.
and just return 404 not found if i access my jpg file

**Comment by Sopamo** [comment]
This is probably an issue with your specific deployment rather than with laravel-filepond. Are you moving the file from the tmp location to a proper storage location?
Do you have any cronjobs which might be interfering here?

**Comment by 0length** [comment]
Yeah thats true.. I just deploy my app to herokuapp and thats happen.. Then i try to deploy in my own vps with docker..  Thats not happen..
